### ISSUE TITLE
SRS: Review Section 2.2 - "Product Functions"

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#31]

**Comment by EngineerFaunce** [comment]
Edits I made:
* Removed mention of audio content so that we can focus primarily on video content going forward
* Removed duplicate product function and fixed numbering

On another note, the unique identifiers for product functions changes after the third function from `REQ-PF-3` to `RED-PF-4`. I'm not sure if this change was intentional or not.
