### ISSUE TITLE
Determine which login strategies to support

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#35]
Right now, plans are to use Username/Password and Google authentication, additional options include:

- Reddit Login
- Apple
- Twitter
- GitHub
- Linkedin
- Facebook (☹️ )
- Many more

Thoughts?

**Comment by EngineerFaunce** [comment]
Personally, I think Reddit and Twitter login options should be considered. I'm not a huge fan of facebook due to privacy concerns. The others, such as Apple, GitHub and Linkedin don't really fit with skoot since aims to be a social media platform of sorts.

**Comment by DylanBulmer** [comment]
For login strategies, I think the best route is to use [PassportJS](http://www.passportjs.org/) as it can simplify the process a ton. Because of that, Apple login should not be used as it is not a strategy PassportJS provides. 

I like most of your ideas @SKaplanOfficial, we should include a social logins. I agree with @EngineerFaunce about Facebook due to the privacy issues, but disagree about GitHub and LinkedIn. I think these two could work out. 

In my opinion we should support logins for various backgrounds to please the majority of people. For this, I believe *skoot* should support the following:

For the average person:
* Reddit
* Twitter
* Google

For developers:
* GitHub

For professionals:
* LinkedIn

For the Gamers:
* Discord

Also for standard login, should we allow login with (username, email, or phone number) and password with 2FA if enabled?

Please comment your thoughts. 😃

**Comment by EngineerFaunce** [comment]
> Also for standard login, should we allow login with (username, email, or phone number) and password with 2FA if enabled?

If I understand your question right, I'd say for standard login we could allow username/email + password and then if the user has 2FA enabled, bring up another UI prompt for the user.

**Comment by DylanBulmer** [comment]
The strategies are going to be Google, Twitter, Reddit, and Discord.
