### ISSUE TITLE
Design: Discover Page

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#56]
Need feedback on this mockup:
![discover-page](https://user-images.githubusercontent.com/7865925/79095041-574bbf80-7d27-11ea-8473-5d188b5da7dd.png)
More sections can be added as needed, but this would be the basic layout of the page. Thoughts?

**Comment by EngineerFaunce** [comment]
Looks very good, I especially like the `Random Community` and `Random Video` buttons.

For the tags section, I would make them a little bit smaller. Also the two buttons I mentioned above should be a bit bigger so that it's not a "secret" function of this page.

**Comment by DylanBulmer** [comment]
My only comment is that this design looks huge on smaller 720p screens (like mine). Will mentioned that the tags need to be smaller, but I believe the entire design needs to be a bit smaller, obviously this can change in development since this is just a design concept, but it's just throwing me off. You can even see how large it is relative to the side bar, search bar and the newly added buttons right under the search bar. 

Besides on the size of the content, I think this looks really good!

**Comment by DylanBulmer** [comment]
One thing I just thought, are these new communities including personal communities (PC)? If not, (assuming this is not the case), we will need to make modifications to the Community DB to distinguish PCs from the rest.

Some other options: 
1. We can make it optional to create a PC on account creation
2. Create an option to declare their PC private on account creation
3. In the new communities algorithm, require communities to have a minimum number of members before appearing on the Discovery page.

All of these options can eliminate the spam of new communities being displayed on the discovery page. After some thought, I think all options should be implemented.
